SingImage: "~/singularity-images/trRosetta.sif"
trRosettaPath: "~/trRosetta"
scriptPath: "~/script/"
jhparams: "-N 3 --cpu 8"
databasePath: "~/database/uniref90.fasta"
workdir: "/home/fabiana/"
dockq: "~/script/DockQ.py"
modelpath: "model/"
cns_solve: "home/fabiana/cns_solve_1.3"